// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj04jrBB48SR0tecPysktvSOr5jcSQI0Y',
    appId: '1:493495749462:web:ceb5c35825af7aca3024f7',
    messagingSenderId: '493495749462',
    projectId: 'initial-tour-guide',
    authDomain: 'initial-tour-guide.firebaseapp.com',
    storageBucket: 'initial-tour-guide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwWhApgulQhOTcHzsd1LL1_fJg5APCR4k',
    appId: '1:493495749462:android:11f9cd40e824ff903024f7',
    messagingSenderId: '493495749462',
    projectId: 'initial-tour-guide',
    storageBucket: 'initial-tour-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHV0TXxxf9KZPG7QMOnpjQSP3RlgLvfpE',
    appId: '1:493495749462:ios:515d6842bbefb4793024f7',
    messagingSenderId: '493495749462',
    projectId: 'initial-tour-guide',
    storageBucket: 'initial-tour-guide.firebasestorage.app',
    iosBundleId: 'com.example.tourAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHV0TXxxf9KZPG7QMOnpjQSP3RlgLvfpE',
    appId: '1:493495749462:ios:515d6842bbefb4793024f7',
    messagingSenderId: '493495749462',
    projectId: 'initial-tour-guide',
    storageBucket: 'initial-tour-guide.firebasestorage.app',
    iosBundleId: 'com.example.tourAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj04jrBB48SR0tecPysktvSOr5jcSQI0Y',
    appId: '1:493495749462:web:9abb49c622f739933024f7',
    messagingSenderId: '493495749462',
    projectId: 'initial-tour-guide',
    authDomain: 'initial-tour-guide.firebaseapp.com',
    storageBucket: 'initial-tour-guide.firebasestorage.app',
  );
}
